### PR TITLE
WIP Vite svelte configuration

### PR DESCRIPTION
**Pull request by lgharib**

### CODE REVIEW

**Comment by mauroporras** [comment]
Hey @lgharib, is this PR ready for review? I noticed it's not building. Is it a work in progress?

**Comment by mauroporras** [comment]
@lgharib use a different PR for changes that are not directly related to the Vite migration please.

**Comment by phtaylor** [comment]
It looks like most of these changes are actually reverting changes made since this branch was created. Maybe an issue with Git. 

It looks like one massive commit changed 33 files at once, which is worrying.
This branch should be closed and a new one created with only the 2 'minor' changes required for Vite.

**Comment by moh60** [comment]
#69

**Comment by mauroporras** [comment]
https://github.com/ZeaInc/zea-svelte-template/pull/69#issuecomment-874369830

**Pull request closed without merging**
